language: php
php:
    - '8.0'
    - '8.1'
    - 'nightly'
jobs:
    allow_failures:
        - php: 'nightly'
install:
    - composer install --dev --no-scripts --no-suggest

script:
    - vendor/bin/phpcs -p ./src
    - vendor/bin/phpstan analyse -c phpstan.neon
