resources:
    RZ\Roadiz\UserBundle\Api\Dto\UserOutput:
        shortName: User
        types:
            - User
        operations:
            # Current user information operation MUST be declared AFTER ApiPlatform\Metadata\Get
            # to avoid conflict with IRI generation.
            api_user_information:
                method: 'GET'
                class: ApiPlatform\Metadata\Get
                # Path must be different from item operation to avoid conflict
                uriTemplate: '/me'
                provider: RZ\Roadiz\UserBundle\State\UserTokenProvider
                normalizationContext:
                    groups: ['user', 'user_personal', 'user_security']
                    enable_max_depth: true
                openapi:
                    summary: Get current user (JWT) information
                    description: |
                        Get current user (JWT) information
                    tags:
                        - User
