---
parameters:
    env(USER_PASSWORD_RESET_URL): 'loginResetPage'
    env(USER_VALIDATION_URL): 'http://example.test/my-account/validate'
    env(USER_PASSWORD_RESET_EXPIRES_IN): '900'
    env(USER_VALIDATION_EXPIRES_IN): '3600'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $passwordResetUrl: '%roadiz_user.password_reset_url%'
            $userValidationUrl: '%roadiz_user.user_validation_url%'
            $passwordResetExpiresIn: '%roadiz_user.password_reset_expires_in%'
            $userValidationExpiresIn: '%roadiz_user.user_validation_expires_in%'
            $publicUserRoleName: '%roadiz_user.public_user_role_name%'
            $passwordlessUserRoleName: '%roadiz_user.passwordless_user_role_name%'
            $emailValidatedRoleName: '%roadiz_user.email_validated_role_name%'
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    RZ\Roadiz\UserBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'
            - '../src/Event/'
            - '../src/Security/'

    RZ\Roadiz\UserBundle\State\UserSignupProcessor:
        tags: [ 'api_platform.state_processor' ]

    RZ\Roadiz\UserBundle\State\PasswordlessUserSignupProcessor:
        tags: [ 'api_platform.state_processor' ]
