---
parameters:
    env(USER_PASSWORD_RESET_URL): 'loginResetPage'
    env(USER_PASSWORD_RESET_EXPIRES_IN): '600'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $passwordResetUrl: '%roadiz_user.password_reset_url%'
            $passwordResetExpiresIn: '%roadiz_user.password_reset_expires_in%'

    RZ\Roadiz\UserBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'
            - '../src/Event/'

    RZ\Roadiz\UserBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
