---
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    RZ\Roadiz\UserBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'
            - '../src/Event/'

    RZ\Roadiz\UserBundle\Controller\:
        resource: '../src/Controller/'
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']
